# permissions for end users to view cronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cronjob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-viewer-role
rules:
- apiGroups:
  - batch.k8s.shivamthabe.me
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.k8s.shivamthabe.me
  resources:
  - cronjobs/status
  verbs:
  - get
